services:

  # Base de données PostgreSQL utilisée par Dolibarr
  postgres:
    image: postgres:16
    container_name: sae-dolibarr-postgres

    environment:
      POSTGRES_DB: dolibarr
      POSTGRES_USER: dolibarr
      POSTGRES_PASSWORD: dolibarr_dev_password

    # Conservation des données PostgreSQL après arrêt du conteneur
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - dolibarr_network

    # Vérifie que PostgreSQL est réellement prêt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dolibarr -d dolibarr"]
      interval: 5s
      timeout: 5s
      retries: 10


  # Serveur Web Apache/PHP contenant Dolibarr
  dolibarr:
    build:
      context: ./docker/dolibarr
      dockerfile: Dockerfile

    image: sae-dolibarr:24.0.1
    container_name: sae-dolibarr

    # Attend que PostgreSQL soit opérationnel avant de démarrer Dolibarr
    depends_on:
      postgres:
        condition: service_healthy

    # Variables utilisées par docker-entrypoint.sh
    # pour générer automatiquement conf.php
    environment:
      DOLIBARR_URL_ROOT: "http://localhost:8080"

      DOLIBARR_DB_HOST: "postgres"
      DOLIBARR_DB_PORT: "5432"
      DOLIBARR_DB_NAME: "dolibarr"
      DOLIBARR_DB_USER: "dolibarr"
      DOLIBARR_DB_PASSWORD: "dolibarr_dev_password"

      DOLIBARR_INSTANCE_UNIQUE_ID: "sae-dolibarr"

    # Accès à Dolibarr depuis le PC
    ports:
      - "8080:80"

    # Conservation des documents générés ou importés dans Dolibarr
    volumes:
      - dolibarr_documents:/var/lib/dolibarr/documents

    networks:
      - dolibarr_network


# Réseau privé permettant à Dolibarr de communiquer avec PostgreSQL
networks:
  dolibarr_network:


# Volumes persistants
volumes:
  postgres_data:
  dolibarr_documents: